TimeTrail Sound Setting
Makkuusen/TimingSystem pull request #98
Opened 2022-09-25 20:10 UTC by Pigalala

Adds `/tt sound` which toggles the pb sound. Setting is stored in ts_players : ttSound.
Testing may still be needed.

Closes #97 

Databases will need to run the following statement for this update to work:
``ALTER TABLE `ts_players` ADD `ttSound` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'true' AFTER `boat`;``

2022-09-25 20:20 UTC, Makkuusen commented on src/main/java/me/makkuusen/timing/system/ApiUtilities.java
> +    private static final List<String> rejectedWords = Arrays.asList("random", "r", "cancel", "c", "help", "verbose", "sounds");
sounds should only be sound

2022-09-25 20:30 UTC, Pigalala commented on src/main/java/me/makkuusen/timing/system/ApiUtilities.java
> +    private static final List<String> rejectedWords = Arrays.asList("random", "r", "cancel", "c", "help", "verbose", "sounds");
brah
I'll fix tomorrow

2022-09-26 14:37 UTC, Pigalala commented on src/main/java/me/makkuusen/timing/system/ApiUtilities.java
> +    private static final List<String> rejectedWords = Arrays.asList("random", "r", "cancel", "c", "help", "verbose", "sounds");
ok it is fixed now i hope you're happy

2022-09-26 17:39 UTC, Makkuusen requested changes
As ttSound is stored as true/false I would prefer if it was done the same way as other booleans like toggleOpen in ts_tracks. I also think it would be cool to rename "ttsound" to "toggleSound".

So for the database table creation add this instead " `toggleSound` tinyint(1) NOT NULL"

And then update the constructor of TPlayer to be data.get("toggleSound"), and make any necessary changes to the setTTSound command as well.

2022-09-26 20:06 UTC, Pigalala commented
``ALTER TABLE `ts_players` ADD `toggleSound` tinyint(1) DEFAULT 1 AFTER `boat`;`` i haven't tested this statement i hope it works.
/tt togglesound

2022-09-26 20:15 UTC, merged